[package]
name = "opengl-from-scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = { path = "lib/gl", version = "0.1.0" }

[dependencies.sdl2]
version = "0.35.2"
features = ["bundled", "static-link"]

[features]
gl_debug = ["gl/debug"]
